version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: postgresss
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: app_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      target: development
    container_name: academics-pro
    environment:
      DATABASE_URL: postgresql://myuser:mypassword@localhost:5432/mydatabase
      PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres

volumes:
  postgres_data:

# docker-compose up --build
